#!/usr/bin/env python3
"""Build matchups.json from the BodyThoseFools sheet markdown.

Usage:
    build_matchups.py <input> [<output_json>]

<input> may be either:
  - the raw Drive tool-result file (JSON with a "fileContent" key), or
  - a plain markdown file containing the matchup table.

Output defaults to matchups.json next to this script's parent (the skill dir).
Reproduces every matchup comment verbatim (typos included). No em-dash sanitizing
is needed because the sheet contains none; if that ever changes, fix the source,
not this file.
"""
import io
import json
import os
import sys


def _norm(name):
    """Normalize a champion name to a lookup key: lowercase, drop non-alphanumerics."""
    return "".join(ch for ch in name.lower() if ch.isalnum())


def load_markdown(path):
    raw = io.open(path, encoding="utf-8").read()
    try:
        obj = json.loads(raw)
        if isinstance(obj, dict) and "fileContent" in obj:
            return obj["fileContent"]
    except (ValueError, TypeError):
        pass
    return raw


def parse_table(md):
    rows = {}
    order = []
    for line in md.split("\n"):
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 4:
            continue
        champ = cells[0]
        # Skip header and separator rows.
        if champ.lower().startswith("champions") or set(champ) <= set(":- "):
            continue
        if not champ:
            continue
        rating = cells[2]
        advice = cells[3]
        runes = cells[4] if len(cells) > 4 else ""
        key = _norm(champ)
        rows[key] = {
            "name": champ,
            "rating": rating,
            "advice": advice,
            "runes": runes,
        }
        order.append(key)
    return rows, order


def main():
    if len(sys.argv) < 2:
        print("usage: build_matchups.py <input> [<output_json>]", file=sys.stderr)
        return 2
    src = sys.argv[1]
    skill_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(skill_dir, "matchups.json")

    md = load_markdown(src)
    rows, order = parse_table(md)

    data = {
        "_meta": {
            "source": "BodyThoseFools Azir Matchup Spreadsheet",
            "driveFileId": "YOUR_DRIVE_FILE_ID",
            "note": "Auto-generated by build_matchups.py. Do not hand-edit; "
                    "regenerate from the user's Drive copy via /azir-matchup --refresh. "
                    "Comments are verbatim from the sheet, typos included.",
        },
        "champions": {k: rows[k] for k in order},
    }
    io.open(out, "w", encoding="utf-8").write(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    )
    empties = sum(1 for k in order if not rows[k]["advice"])
    print("wrote {} ({} champions, {} with empty advice)".format(out, len(order), empties))
    return 0


if __name__ == "__main__":
    sys.exit(main())
